apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketing-config
  namespace: ticketing
data:
  HOLD_TTL_MIN: "15"
  PAYMENT_FAILURE_RATE: "0.05"
  CATALOG_URL: "http://catalog-service:8002"
  SEATING_URL: "http://seating-service:8003"
  PAYMENT_URL: "http://payment-service:8005"
  USER_URL: "http://user-service:8001"
  NOTIFY_URL: "http://notification-service:8006"
